#!/usr/bin/env python3
"""Scan RC evidence while recognizing only strictly validated technical metadata.

The repository-wide artifact scanner remains authoritative for secrets and PII.
This wrapper suppresses only exact PII fingerprints generated by synthetic,
loopback-only RC metadata whose key, value, artifact path, and enclosing schema
all satisfy a narrow contract. Secret/JWT/token findings are never suppressed.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import urlsplit

SECURITY_DIR = Path(__file__).resolve().parents[1] / "security"
if str(SECURITY_DIR) not in sys.path:
    sys.path.insert(0, str(SECURITY_DIR))

from scanner import (  # noqa: E402
    Finding,
    _PII_PATTERNS,
    _fingerprint,
    bounded_report,
    scan_artifact_files,
    write_report,
)

RC_EVIDENCE_PREFIX = "artifacts/rc-test/"
NETWORK_SAFETY_PATH = f"{RC_EVIDENCE_PREFIX}network-safety.json"
NETWORK_SAFETY_SCHEMA = "nexus.osr.rc-test-network-safety.v1"
SAFE_NAME_RE = re.compile(r"^[A-Za-z0-9_./-]{1,180}$")
CONVERSATION_RE = re.compile(r"^wc_[A-Za-z0-9_-]{8,120}$")
NETWORK_RE = re.compile(
    r"^nexus_(?:(?:rc_test|controlled)_[1-9][0-9]{0,19}|"
    r"pr[1-9][0-9]{0,9}_rc_[1-9][0-9]{0,19})_(?:rc|edge)$"
)
APP_VERSION_RE = re.compile(r"^(?:rc-test|controlled)-[0-9a-f]{12}$")
IMAGE_TAG_RE = re.compile(r"^[a-z0-9][a-z0-9._/-]{0,127}:rc-test-[0-9a-f]{40}$")
BUILD_TIME_RE = re.compile(r"^[0-9]{8}T[0-9]{6}Z$")
MIGRATION_RE = re.compile(r"^[0-9]{8}_[A-Za-z0-9][A-Za-z0-9_.-]{0,70}$")

MIGRATION_KEYS_BY_PATH = {
    f"{RC_EVIDENCE_PREFIX}candidate-manifest.json": {"migration_revision"},
    f"{RC_EVIDENCE_PREFIX}readyz.json": {
        "migration_revision",
        "expected",
        "observed",
    },
}

LOOPBACK_URL_KEYS = {"origin", "browser_origin", "page_url"}
NETWORK_KEYS = {"app_networks", "nginx_networks", "internal_network", "loopback_gateway_network"}


def _is_loopback_url(value: str) -> bool:
    if len(value) > 512 or any(ord(char) < 32 or ord(char) == 127 for char in value):
        return False
    try:
        parsed = urlsplit(value)
        _ = parsed.port
    except ValueError:
        return False
    return (
        parsed.scheme == "http"
        and (parsed.hostname or "").lower() in {"127.0.0.1", "localhost", "::1"}
        and parsed.username is None
        and parsed.password is None
        and not parsed.query
        and not parsed.fragment
    )


def _validated_network_safety_metadata(
    payload: object,
    *,
    path: str,
) -> set[tuple[str, str]]:
    """Return only network values from a complete, internally consistent proof.

    Network names are deliberately not accepted by key alone. The artifact must
    be the exact RC network-safety document, carry the canonical schema, prove it
    did not join the production network, and describe one shared project prefix
    with the expected isolated application and loopback edge networks.
    """

    expected_keys = {
        "app_networks",
        "internal_network",
        "loopback_gateway_network",
        "nginx_networks",
        "production_network_joined",
        "schema",
        "status",
    }
    if path != NETWORK_SAFETY_PATH or not isinstance(payload, dict) or set(payload) != expected_keys:
        return set()
    if (
        payload.get("schema") != NETWORK_SAFETY_SCHEMA
        or payload.get("status") != "pass"
        or payload.get("production_network_joined") is not False
    ):
        return set()

    internal = payload.get("internal_network")
    edge = payload.get("loopback_gateway_network")
    app_networks = payload.get("app_networks")
    nginx_networks = payload.get("nginx_networks")
    if (
        not isinstance(internal, str)
        or not isinstance(edge, str)
        or not isinstance(app_networks, list)
        or not isinstance(nginx_networks, list)
        or len(app_networks) != 1
        or len(nginx_networks) != 2
        or any(not isinstance(value, str) for value in app_networks + nginx_networks)
        or not NETWORK_RE.fullmatch(internal)
        or not NETWORK_RE.fullmatch(edge)
        or not internal.endswith("_rc")
        or not edge.endswith("_edge")
        or internal.rsplit("_", 1)[0] != edge.rsplit("_", 1)[0]
        or app_networks != [internal]
        or set(nginx_networks) != {internal, edge}
    ):
        return set()

    return {
        ("internal_network", internal),
        ("loopback_gateway_network", edge),
        ("app_networks", internal),
        ("nginx_networks", internal),
        ("nginx_networks", edge),
    }


def _is_safe_rc_metadata(*, path: str, key: str, value: str) -> bool:
    if not path.startswith(RC_EVIDENCE_PREFIX):
        return False
    if key in LOOPBACK_URL_KEYS:
        return _is_loopback_url(value)
    if key == "conversation_id":
        return bool(CONVERSATION_RE.fullmatch(value))
    if key == "app_version":
        return bool(APP_VERSION_RE.fullmatch(value))
    if key == "image_tag":
        return bool(IMAGE_TAG_RE.fullmatch(value))
    if key == "build_time":
        return bool(BUILD_TIME_RE.fullmatch(value))
    if key in MIGRATION_KEYS_BY_PATH.get(path, set()):
        return bool(MIGRATION_RE.fullmatch(value))
    return False


def _collect_safe_pii_fingerprints(
    value: object,
    *,
    path: str,
    validated_network_metadata: set[tuple[str, str]],
    key: str = "",
    depth: int = 0,
) -> set[tuple[str, str, str]]:
    if depth > 8:
        return set()
    output: set[tuple[str, str, str]] = set()
    if isinstance(value, dict):
        for raw_key, child in list(value.items())[:200]:
            output.update(
                _collect_safe_pii_fingerprints(
                    child,
                    path=path,
                    validated_network_metadata=validated_network_metadata,
                    key=str(raw_key).strip().lower(),
                    depth=depth + 1,
                )
            )
    elif isinstance(value, list):
        for child in value[:200]:
            output.update(
                _collect_safe_pii_fingerprints(
                    child,
                    path=path,
                    validated_network_metadata=validated_network_metadata,
                    key=key,
                    depth=depth + 1,
                )
            )
    elif isinstance(value, str) and (
        (key, value) in validated_network_metadata
        or _is_safe_rc_metadata(path=path, key=key, value=value)
    ):
        for rule, pattern in _PII_PATTERNS:
            match = pattern.search(value)
            if match:
                output.add((path, f"artifact:{rule}", _fingerprint(rule, path, 0, match.group(0))))
    return output


def _load_json(root: Path, relative: str) -> object | None:
    path = root / relative
    if path.suffix.lower() != ".json" or not path.is_file() or path.is_symlink():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError, RecursionError):
        return None


def scan_rc_artifact_files(root: Path, relative_paths: Iterable[str]) -> tuple[list[Finding], int]:
    paths = sorted(set(relative_paths))
    findings = scan_artifact_files(root, paths)
    safe: set[tuple[str, str, str]] = set()
    for relative in paths:
        payload = _load_json(root, relative)
        if payload is not None:
            safe.update(
                _collect_safe_pii_fingerprints(
                    payload,
                    path=relative,
                    validated_network_metadata=_validated_network_safety_metadata(
                        payload,
                        path=relative,
                    ),
                )
            )
    remaining = [
        finding
        for finding in findings
        if (finding.path, finding.rule, finding.fingerprint) not in safe
    ]
    return remaining, len(findings) - len(remaining)


def _write_failure_summary(root: Path, findings: list[Finding]) -> None:
    evidence_root = root / "artifacts" / "rc-test"
    evidence_root.mkdir(parents=True, exist_ok=True)
    rules = sorted({finding.rule for finding in findings if re.fullmatch(r"[a-z0-9_:.-]{2,80}", finding.rule)})[:10]
    paths = sorted(
        {
            finding.path
            for finding in findings
            if SAFE_NAME_RE.fullmatch(finding.path) and finding.path.startswith(RC_EVIDENCE_PREFIX)
        }
    )[:10]
    payload: dict[str, Any] = {
        "schema": "nexus.osr.rc-test-failure-summary.v1",
        "status": "failed",
        "stage": "artifact-scan",
        "exit_code": 1,
        "reason_code": "artifact_scan_findings",
        "service_states": {},
        "finding_rules": rules,
        "finding_paths": paths,
    }
    (evidence_root / "failure-summary.json").write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".")
    parser.add_argument("--output", required=True)
    parser.add_argument("paths", nargs="+")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    findings, suppressed = scan_rc_artifact_files(root, args.paths)
    write_report(
        Path(args.output),
        bounded_report(
            schema="nexus_security_artifact_scan_v1",
            findings=findings,
            scanned_files=len(args.paths),
            suppressed_count=suppressed,
        ),
    )
    if findings:
        _write_failure_summary(root, findings)
        return 1
    failure_summary = root / "artifacts" / "rc-test" / "failure-summary.json"
    if failure_summary.is_file():
        failure_summary.unlink()
    print(f"RC_ARTIFACT_SCAN_VALID=true files={len(args.paths)} technical_pii_suppressed={suppressed}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
