import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import test from 'node:test'

const root = resolve(import.meta.dirname, '..')
const emailRoute = readFileSync(resolve(root, 'src/routes/email.tsx'), 'utf8')
const router = readFileSync(resolve(root, 'src/router.tsx'), 'utf8')
const apiClient = readFileSync(resolve(root, 'src/lib/api.ts'), 'utf8')
const types = readFileSync(resolve(root, 'src/lib/types.ts'), 'utf8')
const rbac = readFileSync(resolve(root, 'src/lib/rbac.ts'), 'utf8')
const appShell = readFileSync(resolve(root, 'src/layouts/AppShell.tsx'), 'utf8')
const commandPalette = readFileSync(resolve(root, 'src/components/ui/CommandPalette.tsx'), 'utf8')

test('email workbench route uses unified routeAccess RBAC semantics', () => {
  assert.match(router, /EmailRoute/)
  assert.match(router, /@\/routes\/email/)
  assert.match(emailRoute, /path: '\/email'/)
  assert.match(rbac, /'\/email': \{ allOf: \[CAPABILITIES\.ticketRead\], anyOf: \[CAPABILITIES\.outboundDraftSave, CAPABILITIES\.outboundSend\] \}/)
  assert.match(emailRoute, /<RequireCapability requirement=\{routeAccess\['\/email'\]\}>/)
  assert.match(emailRoute, /const emailDraftAccess = \{ allOf: \[CAPABILITIES\.outboundDraftSave\] \}/)
  assert.match(emailRoute, /const emailSendAccess = \{ allOf: \[CAPABILITIES\.outboundSend\] \}/)
  assert.doesNotMatch(emailRoute, /emailWorkbenchAccess/)
})

test('email workbench is reachable from AppShell navigation and command palette', () => {
  assert.match(appShell, /to: '\/email'[\s\S]*label: 'Email 工作台'[\s\S]*access: routeAccess\['\/email'\]/)
  assert.match(appShell, /\{ label: '日常处理', items: \['\/', '\/workspace', '\/webchat', '\/webcall', '\/email', '\/bulletins'\] \}/)
  assert.match(commandPalette, /id: 'email-workbench'[\s\S]*label: '打开 Email 工作台'[\s\S]*to: '\/email'[\s\S]*access: routeAccess\['\/email'\]/)
})

test('email queue filter uses tokenized channel markers instead of loose substring regex', () => {
  assert.match(emailRoute, /const EMAIL_QUEUE_TOKENS = new Set\(\['email', 'mail', 'smtp', 'imap', 'pop3'\]\)/)
  assert.match(emailRoute, /replace\(\/\\be\[-_\\s\]\?mail\\b\/g, 'email'\)/)
  assert.match(emailRoute, /split\(\/\[\^a-z0-9\]\+\/\)\.some\(\(token\) => EMAIL_QUEUE_TOKENS\.has\(token\)\)/)
  assert.doesNotMatch(emailRoute, /\/email\|mail\|smtp\/i/)
})

test('email workbench closes draft save, outbound send, and timeline refresh loops', () => {
  assert.match(apiClient, /saveOutboundDraft: \(ticketId: number, payload: OutboundSendPayload\)/)
  assert.match(apiClient, /`\/api\/tickets\/\$\{ticketId\}\/outbound\/draft`/)
  assert.match(emailRoute, /api\.saveOutboundDraft\(activeCase\.id, \{ channel: 'email', subject: subject\.trim\(\), body: body\.trim\(\), attachment_ids: attachmentIds \}\)/)
  assert.match(emailRoute, /api\.sendOutboundMessage\(activeCase\.id, \{ channel: 'email', subject: subject\.trim\(\), body: body\.trim\(\), attachment_ids: attachmentIds \}\)/)
  assert.match(emailRoute, /api\.ticketOutboundChannelCapabilities\(activeCase\.id\)/)
  assert.match(emailRoute, /api\.ticketTimeline\(selectedId as number, \{ limit: 30 \}\)/)
  assert.match(emailRoute, /invalidateQueries\(\{ queryKey: \['ticketTimeline', activeCase\.id\] \}\)/)
  assert.match(emailRoute, /保存草稿和发送都会进入 ticket timeline\/ticket event audit/)
  assert.doesNotMatch(emailRoute, /\bfetch\s*\(/)
})

test('email composer binds ticket attachments to outbound draft and send payloads', () => {
  assert.match(types, /attachment_ids\?: number\[\]/)
  assert.match(emailRoute, /const \[attachmentIds, setAttachmentIds\] = useState<number\[\]>\(\[\]\)/)
  assert.match(emailRoute, /activeCase\.attachments \?\? \[\]/)
  assert.match(emailRoute, /data-testid="email-workbench-attachments"/)
  assert.match(emailRoute, /supports_attachments/)
  assert.match(emailRoute, /function toggleAttachment\(attachmentId: number\)/)
  assert.match(emailRoute, /setAttachmentIds\(\[\]\)/)
})

test('email composer uploads external ticket attachments through unified API client', () => {
  assert.match(apiClient, /uploadTicketAttachment: \(ticketId: number, file: File, visibility = 'external'\)/)
  assert.match(apiClient, /`\/api\/tickets\/\$\{ticketId\}\/attachments`/)
  assert.match(emailRoute, /const \[uploadedAttachments, setUploadedAttachments\] = useState<SystemAttachment\[\]>\(\[\]\)/)
  assert.match(emailRoute, /api\.uploadTicketAttachment\(activeCase\.id, file, 'external'\)/)
  assert.match(emailRoute, /data-testid="email-workbench-attachment-upload"/)
  assert.match(emailRoute, /type="file"/)
  assert.match(emailRoute, /multiple/)
  assert.match(emailRoute, /function handleAttachmentUpload\(event: ChangeEvent<HTMLInputElement>\)/)
  assert.match(emailRoute, /const MAX_EMAIL_ATTACHMENTS = 10/)
  assert.match(emailRoute, /files\.length > MAX_EMAIL_ATTACHMENTS - attachmentIds\.length/)
  assert.doesNotMatch(emailRoute, /availableAttachments\.slice\(0, 8\)/)
  assert.match(emailRoute, /mergeAttachmentIds\(attachments\.map\(\(attachment\) => attachment\.id\)\)/)
  assert.doesNotMatch(emailRoute, /\bfetch\s*\(/)
})

test('email timeline exposes provider delivery status and dead-message retry controls', () => {
  assert.match(apiClient, /requeueOutboundMessage: \(messageId: number\) => request<RuntimeRecoveryResult>\(`\/api\/admin\/outbound\/\$\{messageId\}\/requeue`, \{ method: 'POST' \}\)/)
  assert.match(emailRoute, /const emailRetryAccess = \{ allOf: \[CAPABILITIES\.runtimeManage\] \}/)
  assert.match(emailRoute, /const canRequeueOutbound = canAccess\(session\.data, emailRetryAccess\)/)
  assert.match(emailRoute, /data-testid="email-provider-delivery-status"/)
  assert.match(emailRoute, /provider_status/)
  assert.match(emailRoute, /failure_reason/)
  assert.match(emailRoute, /api\.requeueOutboundMessage\(messageId\)/)
  assert.match(emailRoute, /window\.confirm\(`确认重排 outbound message #\$\{messageId\}/)
  assert.match(emailRoute, /client\.invalidateQueries\(\{ queryKey: \['ticketTimeline', selectedId\] \}\)/)
  assert.doesNotMatch(emailRoute, /\bfetch\s*\(/)
})

test('email delivery receipts use real provider event API and render receipt evidence', () => {
  assert.match(types, /export type EmailDeliveryReceiptPayload/)
  assert.match(types, /export interface EmailDeliveryReceiptResult/)
  assert.match(apiClient, /recordEmailDeliveryReceipt: \(ticketId: number, messageId: number, payload: EmailDeliveryReceiptPayload\) => request<EmailDeliveryReceiptResult>\(`\/api\/tickets\/\$\{ticketId\}\/email\/outbound\/\$\{messageId\}\/delivery-receipt`/)
  assert.match(emailRoute, /const emailDeliveryReceiptAccess = \{ allOf: \[CAPABILITIES\.runtimeManage\] \}/)
  assert.match(emailRoute, /const EMAIL_DELIVERY_STATUSES = \['accepted', 'delivered', 'opened', 'deferred', 'bounced', 'failed', 'rejected', 'complained'\] as const/)
  assert.match(emailRoute, /data-testid="email-delivery-receipt-recorder"/)
  assert.match(emailRoute, /api\.recordEmailDeliveryReceipt\(activeCase\.id, messageId as number/)
  assert.match(emailRoute, /providerField\(item, 'delivery_status'\)/)
  assert.match(emailRoute, /providerField\(item, 'delivery_receipt_provider'\)/)
  assert.match(emailRoute, /providerField\(item, 'delivery_receipt_id'\)/)
  assert.match(emailRoute, /providerField\(item, 'delivery_receipt_at'\)/)
  assert.match(emailRoute, /Delivery Receipt \/ Provider Event/)
  assert.doesNotMatch(emailRoute, /\bfetch\s*\(/)
})

test('email timeline exposes mailbox thread and SMTP message identity', () => {
  assert.match(emailRoute, /providerField\(item, 'mailbox_thread_id'\)/)
  assert.match(emailRoute, /providerField\(item, 'mailbox_message_id'\)/)
  assert.match(emailRoute, /providerField\(item, 'mailbox_references'\)/)
  assert.match(emailRoute, /thread \{sanitizeDisplayText\(mailboxThreadId\)\}/)
  assert.match(emailRoute, /message-id \{sanitizeDisplayText\(mailboxMessageId\)\}/)
  assert.match(emailRoute, /references \{sanitizeDisplayText\(mailboxReferences\)\}/)
  assert.doesNotMatch(emailRoute, /\bfetch\s*\(/)
})

test('email inbound sync uses unified API client and renders provider mailbox evidence', () => {
  assert.match(types, /export type InboundEmailPayload/)
  assert.match(types, /export interface InboundEmailIngestResult/)
  assert.match(apiClient, /ingestInboundEmail: \(ticketId: number, payload: InboundEmailPayload\) => request<InboundEmailIngestResult>\(`\/api\/tickets\/\$\{ticketId\}\/email\/inbound`/)
  assert.match(emailRoute, /const emailInboundSyncAccess = \{ allOf: \[CAPABILITIES\.runtimeManage\] \}/)
  assert.match(emailRoute, /const canSyncInbound = canAccess\(session\.data, emailInboundSyncAccess\)/)
  assert.match(emailRoute, /data-testid="email-inbound-sync"/)
  assert.match(emailRoute, /api\.ingestInboundEmail\(activeCase\.id/)
  assert.match(emailRoute, /client\.invalidateQueries\(\{ queryKey: \['ticketTimeline', activeCase\.id\] \}\)/)
  assert.match(emailRoute, /sourceType === 'inbound_email'/)
  assert.match(emailRoute, /data-testid="email-inbound-provider-status"/)
  assert.match(emailRoute, /providerField\(item, 'provider_message_id'\)/)
  assert.match(emailRoute, /providerField\(item, 'mailbox_thread_id'\)/)
  assert.doesNotMatch(emailRoute, /\bfetch\s*\(/)
})
