from __future__ import annotations

from ..services.domain_intelligence.registry import DomainPack
from ..services.domain_intelligence.schemas import ActionBoundary, AnswerPlanType, DomainIntent, EvidenceClass


LOGISTICS_DOMAIN_PACK = DomainPack(
    key="logistics",
    description="First validation domain pack for parcel, delivery, pickup, tracking, claims, and support operations.",
    intents=(
        DomainIntent(
            key="tracking_status",
            domain="logistics",
            description="Customer asks for live parcel or waybill status.",
            aliases=("where is my parcel", "track", "tracking", "waybill", "current status", "latest scan", "物流", "运单", "单号", "包裹在哪里", "查一下"),
            rewrite_terms=("tracking status", "live shipment status", "waybill lookup", "delivery scan"),
            evidence_class=EvidenceClass.LIVE_STATUS,
            action_boundary=ActionBoundary.TOOL_REQUIRED,
            allowed_plan_types=(AnswerPlanType.TOOL_CALL, AnswerPlanType.CLARIFY),
            requires_tool_boundary=True,
            tool_keys=("tracking",),
        ),
        DomainIntent(
            key="delivery_attempt_failed.recipient_absent",
            domain="logistics",
            description="Delivery attempt failed because recipient was absent or unavailable.",
            aliases=("courier arrived while i was not home", "courier came while i was not home", "not home", "not at home", "missed delivery", "delivery attempt", "courier arrived", "courier came", "driver came", "no one was available", "recipient not home", "客户不在家", "不在家", "派送失败", "没人", "无人签收"),
            rewrite_terms=("recipient absent", "missed delivery attempt", "failed delivery attempt", "redelivery policy", "next delivery attempt"),
            evidence_class=EvidenceClass.POLICY,
            action_boundary=ActionBoundary.NONE,
            allowed_plan_types=(AnswerPlanType.DIRECT_ANSWER, AnswerPlanType.GUIDED_ANSWER),
        ),
        DomainIntent(
            key="redelivery",
            domain="logistics",
            description="Customer asks whether another delivery attempt will happen.",
            aliases=("deliver again", "redelivery", "second attempt", "try again", "again tomorrow", "再派送", "再次派送", "二次派送", "重派"),
            rewrite_terms=("redelivery", "second delivery attempt", "next working day delivery attempt"),
            evidence_class=EvidenceClass.POLICY,
            action_boundary=ActionBoundary.NONE,
            allowed_plan_types=(AnswerPlanType.DIRECT_ANSWER, AnswerPlanType.GUIDED_ANSWER),
        ),
        DomainIntent(
            key="address_change",
            domain="logistics",
            description="Customer asks to change address, phone, postcode, delivery place, or delivery instructions.",
            aliases=("change address", "update address", "wrong address", "correct address", "postal code is wrong", "deliver to another", "改地址", "地址写错", "修改地址", "更改地址", "邮编错"),
            rewrite_terms=("address change request", "recipient verification", "delivery address update", "operation boundary"),
            evidence_class=EvidenceClass.CUSTOMER_CLAIM,
            action_boundary=ActionBoundary.VERIFICATION_REQUIRED,
            allowed_plan_types=(AnswerPlanType.TOOL_PREPARE, AnswerPlanType.CLARIFY, AnswerPlanType.HANDOFF),
            requires_verification=True,
            requires_tool_boundary=True,
            tool_keys=("address_update",),
        ),
        DomainIntent(
            key="refusal",
            domain="logistics",
            description="Customer or recipient wants to refuse or reject a parcel.",
            aliases=("refuse parcel", "refusal", "reject parcel", "return to sender", "拒收", "拒签", "退回"),
            rewrite_terms=("parcel refusal request", "recipient verification", "return boundary"),
            evidence_class=EvidenceClass.CUSTOMER_CLAIM,
            action_boundary=ActionBoundary.VERIFICATION_REQUIRED,
            allowed_plan_types=(AnswerPlanType.TOOL_PREPARE, AnswerPlanType.HANDOFF, AnswerPlanType.CLARIFY),
            requires_verification=True,
            requires_tool_boundary=True,
            tool_keys=("refusal",),
        ),
        DomainIntent(
            key="cancellation",
            domain="logistics",
            description="Customer asks to cancel or stop a delivery or order.",
            aliases=("cancel delivery", "cancel order", "stop courier", "no longer need", "取消", "取消订单", "取消派送"),
            rewrite_terms=("cancel request", "order cancellation boundary", "verification required"),
            evidence_class=EvidenceClass.CUSTOMER_CLAIM,
            action_boundary=ActionBoundary.VERIFICATION_REQUIRED,
            allowed_plan_types=(AnswerPlanType.TOOL_PREPARE, AnswerPlanType.HANDOFF, AnswerPlanType.CLARIFY),
            requires_verification=True,
            requires_tool_boundary=True,
            tool_keys=("cancel",),
        ),
        DomainIntent(
            key="complaint_escalation",
            domain="logistics",
            description="Customer wants to complain, escalate, or create a formal support case.",
            aliases=("complain", "complaint", "escalate", "manager", "formal complaint", "driver was rude", "投诉", "升级", "人工处理", "主管"),
            rewrite_terms=("complaint escalation", "support case", "work order", "human review"),
            evidence_class=EvidenceClass.CUSTOMER_CLAIM,
            action_boundary=ActionBoundary.HUMAN_REQUIRED,
            allowed_plan_types=(AnswerPlanType.WORK_ORDER_CREATE, AnswerPlanType.HANDOFF, AnswerPlanType.CLARIFY),
            requires_tool_boundary=True,
            tool_keys=("work_order_create",),
        ),
        DomainIntent(
            key="proof_of_delivery",
            domain="logistics",
            description="Customer asks for POD, signature, photo, or disputes delivery proof.",
            aliases=("proof of delivery", "pod", "signature", "delivered but not received", "POD", "签收证明", "已签收但没收到", "签收照片"),
            rewrite_terms=("proof of delivery", "delivery dispute", "signature evidence", "work order"),
            evidence_class=EvidenceClass.CUSTOMER_CLAIM,
            action_boundary=ActionBoundary.VERIFICATION_REQUIRED,
            allowed_plan_types=(AnswerPlanType.TOOL_PREPARE, AnswerPlanType.WORK_ORDER_CREATE, AnswerPlanType.HANDOFF),
            requires_verification=True,
            requires_tool_boundary=True,
            tool_keys=("pod", "work_order_create"),
        ),
        DomainIntent(
            key="driver_contact",
            domain="logistics",
            description="Customer asks for courier or driver contact information.",
            aliases=("courier phone", "driver phone", "contact driver", "driver call me", "快递员电话", "司机电话", "联系快递员"),
            rewrite_terms=("driver contact policy", "privacy boundary", "guided answer"),
            evidence_class=EvidenceClass.POLICY,
            action_boundary=ActionBoundary.NONE,
            allowed_plan_types=(AnswerPlanType.GUIDED_ANSWER, AnswerPlanType.CLARIFY, AnswerPlanType.HANDOFF),
        ),
        DomainIntent(
            key="sla_delay",
            domain="logistics",
            description="Customer asks about delay, delivery promise, or service-level timing.",
            aliases=("late", "delay", "delivery sla", "how long", "not moved", "超时", "延误", "时效", "多久"),
            rewrite_terms=("delivery delay", "SLA policy", "service timing", "tracking boundary"),
            evidence_class=EvidenceClass.POLICY,
            action_boundary=ActionBoundary.NONE,
            allowed_plan_types=(AnswerPlanType.GUIDED_ANSWER, AnswerPlanType.TOOL_CALL, AnswerPlanType.CLARIFY),
        ),
        DomainIntent(
            key="pickup_issue",
            domain="logistics",
            description="Pickup was missed, delayed, or needs a change.",
            aliases=("pickup", "not collected", "courier did not come for pickup", "揽收", "取件", "没来取件"),
            rewrite_terms=("pickup issue", "pickup work order", "pickup tracking"),
            evidence_class=EvidenceClass.CUSTOMER_CLAIM,
            action_boundary=ActionBoundary.TOOL_REQUIRED,
            allowed_plan_types=(AnswerPlanType.TOOL_CALL, AnswerPlanType.WORK_ORDER_CREATE, AnswerPlanType.CLARIFY),
            requires_tool_boundary=True,
            tool_keys=("pickup", "work_order_create"),
        ),
        DomainIntent(
            key="customs_issue",
            domain="logistics",
            description="Customs hold, clearance documents, duty, or import tax questions.",
            aliases=("customs", "clearance", "import tax", "duty", "held by customs", "清关", "海关", "关税"),
            rewrite_terms=("customs issue", "clearance policy", "import duty", "tracking boundary"),
            evidence_class=EvidenceClass.POLICY,
            action_boundary=ActionBoundary.NONE,
            allowed_plan_types=(AnswerPlanType.GUIDED_ANSWER, AnswerPlanType.CLARIFY, AnswerPlanType.TOOL_CALL),
        ),
    ),
)
